# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-05-09 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('username', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='用户名')),
                ('nickname', models.CharField(max_length=30, verbose_name='昵称')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('sign', models.CharField(default=user.models.choice_sign, max_length=50, verbose_name='个人签名')),
                ('info', models.CharField(default='', max_length=150, verbose_name='个人描述')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('avatar', models.ImageField(null=True, upload_to='avatar/')),
                ('login_time', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
